#!/usr/bin/env php
<?php

if (version_compare(PHP_VERSION, '7.4.0', '<')) {
    fwrite(STDERR, "require PHP >= 7.4.0 !\n");
    exit(1);
}

defined('APP_DEBUG') || define('APP_DEBUG', true);
defined('ROOT_PATH') || define('ROOT_PATH', getcwd() . DIRECTORY_SEPARATOR);

$autoloadFiles = [
    __DIR__ . '/../vendor/autoload.php',
    dirname(__DIR__, 3) . '/autoload.php',
];

foreach ($autoloadFiles as $autoloadFile) {
    if (is_file($autoloadFile)) {
        require $autoloadFile;
        exit(0);
    }
}

fwrite(STDERR, "Composer autoload.php not found.\n");
exit(1);
