<?php

declare(strict_types=1);

namespace Think\IdeHelper;

/**
 * IDE Helper Stub 文件生成器
 *
 * 为全局函数和常用 API 生成 PHPDoc 提示
 *
 * @package Think\IdeHelper
 */
class StubGenerator
{
    /**
     * 函数签名列表
     *
     * @var array
     */
    protected array $functions = [];

    /**
     * 构造函数
     */
    public function __construct()
    {
        $this->initializeDefaultFunctions();
    }

    /**
     * 初始化默认函数
     *
     * @return void
     */
    protected function initializeDefaultFunctions(): void
    {
        // ThinkPHP 核心助手函数
        $this->functions = [
            'C' => [
                'doc' => <<<'PHP'
/**
 * 获取配置值
 *
 * @param string|null $key 配置键名（支持点号分隔）
 * @param mixed $default 默认值
 * @return mixed 配置值
 */
PHP,
                'signature' => 'function C(?string $key = null, $default = null)',
            ],
            'E' => [
                'doc' => <<<'PHP'
/**
 * 抛出异常
 *
 * @param string|\Exception $message 异常消息或异常对象
 * @param int $code 错误码
 * @throws \Exception
 */
PHP,
                'signature' => 'function E($message, int $code = 0)',
            ],
            'L' => [
                'doc' => <<<'PHP'
/**
 * 获取语言变量值
 *
 * @param string|null $key 语言键名
 * @param array $params 变量绑定
 * @param string|null $locale 语言区域
 * @return string 语言值
 */
PHP,
                'signature' => 'function L(?string $key = null, array $params = [], ?string $locale = null)',
            ],
            'S' => [
                'doc' => <<<'PHP'
/**
 * 缓存管理
 *
 * @param mixed $name 缓存名称或缓存参数数组
 * @param mixed $value 缓存值
 * @param mixed $options 缓存选项
 * @return mixed
 */
PHP,
                'signature' => 'function S($name, $value = \'\', $options = null)',
            ],
            'U' => [
                'doc' => <<<'PHP'
/**
 * 生成 URL
 *
 * @param string $url URL 路径
 * @param string|array $vars 参数
 * @param bool|string $suffix URL 后缀
 * @param bool $domain 是否显示域名
 * @return string 完整 URL
 */
PHP,
                'signature' => 'function U(string $url = \'\', $vars = \'\', $suffix = true, $domain = false)',
            ],
            'I' => [
                'doc' => <<<'PHP'
/**
 * 获取输入参数
 *
 * 支持从 GET、POST、COOKIE、SERVER 等获取数据
 *
 * @param string|null $key 参数名（支持点号分隔）
 * @param mixed $default 默认值
 * @param string|null $filter 过滤方法
 * @return mixed
 */
PHP,
                'signature' => 'function I(?string $key = null, $default = null, ?string $filter = null)',
            ],
        ];
    }

    /**
     * 生成 _ide_helper.php 文件内容
     *
     * @return string
     */
    public function generate(): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = '/**';
        $lines[] = ' * IDE Helper Stub for ThinkPHP';
        $lines[] = ' * ';
        $lines[] = ' * 自动生成的文件，提供 IDE 类型提示支持';
        $lines[] = ' * @generated by ' . self::class;
        $lines[] = ' */';
        $lines[] = '';

        // 为每个函数生成 stub
        foreach ($this->functions as $name => $function) {
            $lines[] = $this->generateFunctionStub($name, $function);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * 生成单个函数的 stub
     *
     * @param string $name 函数名
     * @param array $function 函数配置
     * @return string
     */
    protected function generateFunctionStub(string $name, array $function): string
    {
        $doc = $function['doc'] ?? '';
        $signature = $function['signature'] ?? '';

        return <<<PHP
{$doc}
if (!function_exists('{$name}')) {
    {$signature}
    {
        // 实际实现在 ThinkPHP 核心中
        // 这里仅提供 IDE 提示
        return \\Think\\Helper\\Functions::{$name}(...func_get_args());
    }
}
PHP;
    }

    /**
     * 添加自定义函数
     *
     * @param string $name 函数名
     * @param string $doc PHPDoc 注释
     * @param string $signature 函数签名
     * @return self
     */
    public function addFunction(string $name, string $doc, string $signature): self
    {
        $this->functions[$name] = [
            'doc' => $doc,
            'signature' => $signature,
        ];

        return $this;
    }

    /**
     * 从配置加载函数映射
     *
     * @return self
     */
    public function loadFromConfig(): self
    {
        if (function_exists('C')) {
            $customFunctions = C('IDE_HELPER_FUNCTIONS');
            if (is_array($customFunctions)) {
                foreach ($customFunctions as $name => $config) {
                    $doc = $config['doc'] ?? '';
                    $signature = $config['signature'] ?? "function {$name}()";
                    $this->addFunction($name, $doc, $signature);
                }
            }
        }

        return $this;
    }
}
